name: Build React Native Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_JVMARGS: -Xmx4g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenJDK 21
        run: |
          sudo apt update
          sudo apt install -y openjdk-21-jdk
          java -version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          cache: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: android

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload APK to S3 with unique name
        run: |
          set -e

          echo "🔍 Verifying AWS variables:"
          echo "  AWS_REGION=$AWS_REGION"
          echo "  S3_BUCKET_NAME=$S3_BUCKET_NAME"
          echo "  S3_BUCKET_PATH=$S3_BUCKET_PATH"

          DATE_TAG=$(date +%Y%m%d-%H%M%S)
          FILE_NAME="app-release-$DATE_TAG-${GITHUB_SHA::7}.apk"

          if [ -n "$S3_BUCKET_PATH" ]; then
            S3_URI="s3://$S3_BUCKET_NAME/$S3_BUCKET_PATH/$FILE_NAME"
            PUBLIC_URL="https://$S3_BUCKET_NAME.s3.$AWS_REGION.amazonaws.com/$S3_BUCKET_PATH/$FILE_NAME"
          else
            S3_URI="s3://$S3_BUCKET_NAME/$FILE_NAME"
            PUBLIC_URL="https://$S3_BUCKET_NAME.s3.$AWS_REGION.amazonaws.com/$FILE_NAME"
          fi

          echo "📤 Uploading to: $S3_URI"

          aws s3 cp android/app/build/outputs/apk/release/app-release.apk "$S3_URI" \
            --region "$AWS_REGION" \
            --endpoint-url "https://s3.$AWS_REGION.amazonaws.com"

          echo "✅ APK uploaded: $PUBLIC_URL"
          echo "::notice title=Download APK::$PUBLIC_URL"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_PATH: ${{ secrets.S3_BUCKET_PATH }}
